// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxIsGTeg5mEouBiWxnY0EnAVDJ-GWrYEw',
    appId: '1:446167274830:web:c3b5e5ac0175ca6e263a1f',
    messagingSenderId: '446167274830',
    projectId: 'fir-c627e',
    authDomain: 'fir-c627e.firebaseapp.com',
    storageBucket: 'fir-c627e.appspot.com',
    measurementId: 'G-3EEHN03F81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMiLM0oV5LeuKZkqaIvBDuLRIKdiqpcNA',
    appId: '1:446167274830:android:09d270a1d76fabf7263a1f',
    messagingSenderId: '446167274830',
    projectId: 'fir-c627e',
    storageBucket: 'fir-c627e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH44mko3zFJZIMsaSUR4r9J-W8McRsGkw',
    appId: '1:446167274830:ios:65da6f1766269a44263a1f',
    messagingSenderId: '446167274830',
    projectId: 'fir-c627e',
    storageBucket: 'fir-c627e.appspot.com',
    iosClientId: '446167274830-upic3er2g66hc7cogtrg1022dsbp61cd.apps.googleusercontent.com',
    iosBundleId: 'com.lds.firstflutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH44mko3zFJZIMsaSUR4r9J-W8McRsGkw',
    appId: '1:446167274830:ios:65da6f1766269a44263a1f',
    messagingSenderId: '446167274830',
    projectId: 'fir-c627e',
    storageBucket: 'fir-c627e.appspot.com',
    iosClientId: '446167274830-upic3er2g66hc7cogtrg1022dsbp61cd.apps.googleusercontent.com',
    iosBundleId: 'com.lds.firstflutterapp',
  );
}
